apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
    app: udagram
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        service: frontend
        api: external
        app: udagram       
    spec:
      containers:
      - image: {{ .Values.image_repo }}/udagram-frontend:{{ .Values.tagfrontend }}
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"                
      restartPolicy: Always