apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
    app: udagram
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        service: reverseproxy
        app: udagram
    spec:
      containers:
      - image: {{ .Values.image_repo }}/udagram-reverseproxy:{{ .Values.tag }}
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always