name: backend-feed-ci

on:
  push:
    branches:
      - 'master'
    paths:
      - udagram-api-feed/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Create tag
        id: vars
        run: echo "::set-output name=sha_short::feed-tag-$(git rev-parse --short HEAD)"
      - 
        name: Check tag
        run: echo ${{ steps.vars.outputs.sha_short }}
      -
        name: Build and push udagram-api-feed
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-feed
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:latest, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:${{ steps.vars.outputs.sha_short }}
      - 
        name: Update tag to Helm values
        run: |
          echo https://minhman1504:${{ secrets.API_TOKEN_GITHUB }}@github.com/minhman1504/Udacity-Capstone-Project-Config.git
          git clone https://minhman1504:${{ secrets.API_TOKEN_GITHUB }}@github.com/minhman1504/Udacity-Capstone-Project-Config.git
          cd Udacity-Capstone-Project-Config
          git config user.name "minhman1504"
          git config user.email "minhman1504@gmail.com"
          
          new_tag=${{ steps.vars.outputs.sha_short }}
          current_tag=$(cat ./helm/values.yaml | grep backendfeed: | awk '{print $2}')
          sed -i "s/$current_tag/$new_tag/" ./helm/values.yaml
          git add .
          git commit -m "update new udagram-api-feed tag $current_tag"
          git push origin master
          
