name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push udagram-api-feed
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-feed
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:latest, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:v.0.0.${{ github.run_attempt }}
      -
        name: Build and push udagram-api-user
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-user
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-user:latest, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-user:v.0.0.${{ github.run_attempt }}
      -
        name: Build and push udagram-frontend
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-frontend:latest, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-frontend:v.0.0.${{ github.run_attempt }}
      -
        name: Build and push udagram-reverseproxy
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-reverseproxy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-reverseproxy:latest, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-reverseproxy:v.0.0.${{ github.run_attempt }}
