name: reverseproxy-ci

on:
  push:
    branches:
      - 'master'
    paths:
      - udagram-reverseproxy/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Create tag
        id: vars
        run: echo "::set-output name=sha_short::reverseproxy-tag-$(git rev-parse --short HEAD)"
      - 
        name: Check tag
        run: echo ${{ steps.vars.outputs.sha_short }}
      -
        name: Build and push udagram-reverseproxy
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-reverseproxy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-reverseproxy:latest, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-reverseproxy:${{ steps.vars.outputs.sha_short }}
      - 
        name: Update tag to Helm values
        run: |
          new_tag=${{ steps.vars.outputs.sha_short }}
          current_tag=$(cat ./helm/values.yaml | grep reverseproxy: | awk '{print $2}')
          sed -i "s/$current_tag/$new_tag/" ./helm/values.yaml
      -
        name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          commit_message: CI Version updated
